version: '3'

services:
  backend:
    build:
      context: ./coderine-backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: coderine
      DB_USERNAME: root
      DB_PASSWORD: toor

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: coderine
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - ./coderine-backend/docker/db:/docker-entrypoint-initdb.d
  
  frontend:
    build:
      context: ./coderine-frontend/
      dockerfile: Dockerfile
    ports:
      - "80:8080"
